/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YXlI6TElAjc
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function AuthTemplate() {
  return (
    <div className="min-h-screen bg-[#f0f2f5] flex">
      <div className="w-1/2 bg-[#004643] p-12 text-white flex flex-col justify-between">
        <div>
          <img
            alt="KONFAM Esusu logo"
            className="h-10 w-10"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
          <h1 className="mt-4 text-4xl font-bold">KONFAM Esusu</h1>
          <p className="mt-4 text-lg">Welcome to KONFAM Esusu</p>
          <p className="mt-2 text-sm">
            Revolutionizing your individual and group savings operations with our trusted automated monitoring system.
          </p>
        </div>
        <img
          alt="Hand holding a device"
          className="mt-6"
          height="400"
          src="/placeholder.svg"
          style={{
            aspectRatio: "600/400",
            objectFit: "cover",
          }}
          width="600"
        />
      </div>
      <div className="w-1/2 p-12 flex flex-col justify-center">
        <Link className="text-sm text-[#004643] hover:underline mb-8 inline-block" href="#">
          Back to Homepage
        </Link>
        <div className="max-w-md mx-auto">
          <h2 className="text-3xl font-bold mb-2">Login</h2>
          <p className="mb-6">We'd love to meet you. Kindly provide your details.</p>
          <form>
            <div className="flex flex-col space-y-4 mb-6">
              <label className="text-sm font-medium" htmlFor="email">
                Email Address
              </label>
              <Input id="email" placeholder="xyz@mail.com" type="email" />
              <label className="text-sm font-medium" htmlFor="password">
                Password
              </label>
              <Input id="password" placeholder="Input Password" type="password" />
              <Link className="text-xs text-[#004643] hover:underline self-end" href="#">
                Forgot Password
              </Link>
            </div>
            <Button className="w-full bg-[#004643] text-white">Login</Button>
            <p className="mt-4 text-center text-sm">
              Don't have an account?
              <Link className="text-[#004643] hover:underline" href="#">
                Create Account
              </Link>
            </p>
          </form>
        </div>
      </div>
    </div>
  )
}
